version: '2'
services:
  db:
    image: postgres
  rabbitmq:
    image: rabbitmq
  web:
    image: thraxil/antisocial
    environment:
      - APP=antisocial
      - SECRET_KEY=dummy-secret-key
      - SETTINGS=settings_compose
    command: manage runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
  celery:
    image: thraxil/antisocial
    command: worker
    environment:
      - APP=antisocial
      - SECRET_KEY=dummy-secret-key
      - SETTINGS=settings_compose
      - C_FORCE_ROOT=true
    volumes:
      - .:/app/
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
  beat:
    image: thraxil/antisocial
    command: beat
    environment:
      - SETTINGS=settings_compose    
      - C_FORCE_ROOT=true
      - SECRET_KEY=docker-compose-secret
    volumes:
      - .:/app/
    links:
      - db
      - rabbitmq
